Repository seker212/IO_Lab_Sem5, pull requests merged in 2020-12, with the labels that each got.

#14 LW
  ClassLibrary/ServerAPM.cs
  Client/App.config
  Client/Client.cs
  Client/Client.csproj
  Client/Properties/AssemblyInfo.cs
  ClientFunctionsLibrary/ClientConnection.cs
  ClientFunctionsLibrary/ClientFunctionsLibrary.csproj
  ClientFunctionsLibrary/Properties/AssemblyInfo.cs
  DBIO.db
  TCPServer.sln
Labels: enhancement

#15 Unit testy gut
  .gitignore
  ClassLibrary/DAL/BaseRepository.cs
  ClassLibrary/DAL/JokeRepository.cs
  ClassLibrary/DAL/UserRepository.cs
  ClassLibrary/JokeSQL.cs
  ClassLibrary/Models/Joke.cs
  ClassLibrary/Models/ServerDatabaseContext.cs
  ClassLibrary/Models/User.cs
  ClassLibrary/UserManager.cs
  DBIO.db
  ServerUnitTests/JokeSQLTests.cs
  ServerUnitTests/Properties/AssemblyInfo.cs
  ServerUnitTests/ServerUnitTests.csproj
  ServerUnitTests/UserManagerTests.cs
  ServerUnitTests/app.config
  TCPServer.sln
Labels: enhancement

#26 Server Library Project Renamed
  DBIO.db
  ServerFunctionsLibrary/AbstractServer.cs
  ServerFunctionsLibrary/DAL/BaseRepository.cs
  ServerFunctionsLibrary/DAL/IRepository.cs
  ServerFunctionsLibrary/DAL/JokeRepository.cs
  ServerFunctionsLibrary/DAL/UserRepository.cs
  ServerFunctionsLibrary/JokeSQL.cs
  ServerFunctionsLibrary/Models/Joke.cs
  ServerFunctionsLibrary/Models/ServerDatabaseContext.cs
  ServerFunctionsLibrary/Models/User.cs
  ServerFunctionsLibrary/Properties/AssemblyInfo.cs
  ServerFunctionsLibrary/ServerAPM.cs
  ServerFunctionsLibrary/ServerFunctionsLibrary.csproj
  ServerFunctionsLibrary/ServerSync.cs
  ServerFunctionsLibrary/TestFile.cs
  ServerFunctionsLibrary/UserManager.cs
  ServerFunctionsLibrary/app.config
  ServerFunctionsLibrary/packages.config
  ServerUnitTests/ServerUnitTests.csproj
  TCPServer.sln
  TCPServer/TCPServer.csproj
Labels: enhancement

#28 Logout action and reenter password
  Client/Client.cs
  ClientFunctionsLibrary/ClientConnection.cs
  DBIO.db
  ServerFunctionsLibrary/ServerAPM.cs
  ServerFunctionsLibrary/UserManager.cs
Labels: enhancement

#31 new help and removed useless condition
  Client/Client.cs
  ServerFunctionsLibrary/ServerAPM.cs
Labels: bug

#32 Fixed gitignore and added backup generation
  .gitignore
  DB_Backups/DBIOBackup_2020-19-12--19-56-57.db
  ServerFunctionsLibrary/ServerAPM.cs
Labels: bug, enhancement

#33 Hosted documention
  Documentation/docfx_project/.gitignore
  Documentation/docfx_project/api/.gitignore
  Documentation/docfx_project/api/index.md
  Documentation/docfx_project/articles/intro.md
  Documentation/docfx_project/articles/toc.yml
  Documentation/docfx_project/docfx.json
  Documentation/docfx_project/index.md
  Documentation/docfx_project/toc.yml
  docs/api/ClientFunctionsLibrary.ClientConnection.html
  docs/api/ClientFunctionsLibrary.html
  docs/api/Program.Test.html
  docs/api/Program.html
  docs/api/TCPServer.AbstractServer.html
  docs/api/TCPServer.DAL.BaseRepository-1.html
  docs/api/TCPServer.DAL.IRepository-1.html
  docs/api/TCPServer.DAL.JokeRepository.html
  docs/api/TCPServer.DAL.UserRepository.html
  docs/api/TCPServer.DAL.html
  docs/api/TCPServer.JokeSQL.html
  docs/api/TCPServer.Models.Joke.html
  docs/api/TCPServer.Models.ServerDatabaseContext.html
  docs/api/TCPServer.Models.User.html
  docs/api/TCPServer.Models.html
  docs/api/TCPServer.ServerAPM.TransmissionDataDelegate.html
  docs/api/TCPServer.ServerAPM.html
  docs/api/TCPServer.ServerSync.html
  docs/api/TCPServer.Tests.JokeSQLTests.html
  docs/api/TCPServer.Tests.UserManagerTests.html
  docs/api/TCPServer.Tests.html
  docs/api/TCPServer.UserManager.html
  docs/api/TCPServer.UserType.html
  docs/api/TCPServer.html
  docs/api/index.html
  docs/api/toc.html
  docs/articles/intro.html
  docs/articles/toc.html
  docs/favicon.ico
  docs/fonts/glyphicons-halflings-regular.eot
  docs/fonts/glyphicons-halflings-regular.svg
  docs/fonts/glyphicons-halflings-regular.ttf
  docs/fonts/glyphicons-halflings-regular.woff
  docs/fonts/glyphicons-halflings-regular.woff2
  docs/index.html
  docs/logo.svg
  docs/manifest.json
  docs/search-stopwords.json
  docs/styles/docfx.css
  docs/styles/docfx.js
  docs/styles/docfx.vendor.css
  docs/styles/docfx.vendor.js
  docs/styles/lunr.js
  docs/styles/lunr.min.js
  docs/styles/main.css
  docs/styles/main.js
  docs/styles/search-worker.js
  docs/toc.html
  docs/xrefmap.yml
Labels: documentation
